CREATE TABLE HOSTELSTUDENTINFO (
    ID INT NOT NULL AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(60) NOT NULL,
    HOSTELFREE FLOAT,
    FLOODTYPE VARCHAR(60) NOT NULL
    , UNIQUE (STUDENT_NAME, FLOODTYPE)
    , PRIMARY KEY (ID)
);
